image: ubuntu:16.04

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y git python-minimal python-pip python-six python-flake8 python-pytest python-setuptools python-wheel python-numpy --no-install-recommends
          - apt-get install -y     python3-minimal python3-pip python3-six python3-flake8 python3-pytest python3-setuptools python3-wheel python3-numpy --no-install-recommends
          - pip install .
          - pip3 install .
          - py.test -v test/
          - py.test-3 -v test/
          - cd test/
          - ./runtests.sh
          - python -m flake8 dijitso/


