image: quay.io/fenicsproject/pipelines

pipelines:
  default:
    - step:
        script:
          - python2 -m flake8 .
          - python3 -m flake8 .
          - pip2 install mpi4py
          - pip3 install mpi4py
          - pip2 install .
          - pip3 install .
          - python2 -m pytest -v test/
          - python3 -m pytest -v test/
          - cd test
          - export MPISIZE=1
          - mpirun -n 1 ./mpipytest.sh
          - export MPISIZE=8
          - mpirun -n 8 ./mpipytest.sh
