image: ubuntu:16.04

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y
              g++ libmpich-dev mpich
              python-dev python3-dev
              python-flake8 python3-flake8
              python-minimal python3-minimal
              python-pip python3-pip
              python-pytest python3-pytest
              python-pytest-cov python3-pytest-cov
              python-setuptools python3-setuptools
              python-wheel python3-wheel
              python-numpy python3-numpy
              --no-install-recommends
          - pip install mpi4py
          - pip3 install mpi4py
          - pip install .
          - pip3 install .
          - cd test
          - export MPISIZE=1
          - mpirun -n 1 ./mpipytest.sh
          - export MPISIZE=8
          - mpirun -n 8 ./mpipytest.sh
          - cd ..
          - python -m flake8 .
          - python3 -m flake8 .
