#!/usr/bin/env python

from __future__ import print_function
import sys
import argparse
import dijitso

def main(argv):
    print("This is the commandline tool for the python module dijitso, currently featureless.")
    return 0

if __name__ == "__main__":
   sys.exit(main(sys.argv))
